name: Seili
dependencies:
- python>=3.6.0
- pip
- ipython
- ipywidgets
- jupyter
- git
- numpy
- matplotlib
- pandas
- scikit-learn>=0.20
- ipykernel
- conda-forge::jupyter_contrib_nbextensions
- conda-forge::jupyterlab
- conda-forge::statsmodels
- conda-forge::biopython
- conda-forge::graphviz
- conda-forge::dcm2niix
- conda-forge::nxviz
- scipy
- seaborn
- imageio
- simplegeneric
- pytables
- openpyxl
- pip:
  - pip
  - opencv-python
  - scikit-image
  - Pillow
  - SimpleITK
  - networkx
  - pandas-profiling
  - xlrd
  - nibabel
  - nilearn
  - joblib
  - dipy
  - eli5
  - pdpbox
  - wand
  - python-louvain
  - pyradiomics
  - fury
  - plotly
#  - tensorflow==2.0.0-beta1
  - tensorflow
  - pydot
  
